services:
  discord-twitter-webhooks:
    image: thelovinator/discord-twitter-webhooks
    container_name: discord-twitter-webhooks
    user: "1000:1000"
    ports:
      - 8000:8000
    volumes:
      - ./data/discord-twitter-webhooks:/home/botuser/.local/share/discord_twitter_webhooks
    restart: unless-stopped
